### ISSUE TITLE
训练所用数据集NAT2021-train的json文件可以上传一下吗

### ISSUE THREAD

**Issue by Hgg12** [vision4robotics/SAM-DA#2]

**Comment by Hgg12** [comment]
__C.DATASET.NAT.ANNO ='./train_dataset/sam_nat/sam_nat_b.json'
__C.DATASET.NAT.ANNO_B ='./train_dataset/sam_nat/sam_nat_b.json'
__C.DATASET.NAT.ANNO_S ='./train_dataset/sam_nat/sam_nat_s.json'
__C.DATASET.NAT.ANNO_T ='./train_dataset/sam_nat/sam_nat_t.json'
__C.DATASET.NAT.ANNO_N ='./train_dataset/sam_nat/sam_nat_n.json'
__C.DATASET.NAT.FRAME_RANGE = 1

**Comment by Hgg12** [comment]
训练时提示/media/w/719A549756118C56/HGG/SAM-DA-main/tracker/BAN/siamban/datasets/../.././train_dataset/sam_nat/sam_nat_b.json'需要数据的json文件

**Comment by Reverie5** [comment]
Jsons have uploaded
